version: 2.1
jobs:
    test:
     docker:
      - image: circleci/node
     steps:
      - run:
          docker version
          echo "Hola darvein"
workflows:
 version:2.1
Hello_DARVIEN:
    jobs:
     - test
