version: 2.1
jobs:
    test:
     docker:
      - image: circleci/node
     steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command:|         
          docker images
          echo "Hola darvein"
          echo "foobar"

workflows:
    version:
    Hello_DARVIEN:
        jobs:
            - test
