version: 2.1
jobs:
    test:
     docker:
      - image: circleci/node
     steps:
      - run:
         command: 
           docker version
           echo "Hola darvein"
workflows:
    version:
    Hello_DARVIEN:
        jobs:
            - test
