version: 2.1
jobs:
    test:
     docker:
      - image: circleci/node
     steps:
      - setup_remote_docker:
      - run:
          command:
            docker images
            echo "Hola darvein"
workflows:
    version:
    Hello_DARVIEN:
        jobs:
            - test
